<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-R0CA6L6" failures="1" tests="15" name="Default test" time="43.398" errors="0" timestamp="2023-06-08T11:15:43 IST">
  <testcase classname="api.utils.ExtentReport" name="failTest" time="0.024">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at api.utils.ExtentReport.failTest(ExtentReport.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- failTest -->
  <testcase classname="api.utils.ExtentReport" name="passTest" time="0.006"/>
  <testcase classname="api.utils.ExtentReport" name="skipTest" time="0.003">
    <skipped/>
  </testcase> <!-- skipTest -->
  <testcase classname="api.demo.tests.SparkReport_PetTest" name="TestPostPet" time="11.296"/>
  <testcase classname="api.demo.tests.SparkReport_PetTest" name="TestGetpet" time="1.84"/>
  <testcase classname="api.demo.tests.SparkReport_PetTest" name="TestPutPet" time="3.675"/>
  <testcase classname="api.demo.tests.SparkReport_PetTest" name="TestDeletePet" time="1.83"/>
  <testcase classname="api.demo.tests.ExtentReport_PetTest" name="TestPostPet" time="1.729"/>
  <testcase classname="api.demo.tests.ExtentReport_PetTest" name="TestGetpet" time="1.724"/>
  <testcase classname="api.demo.tests.ExtentReport_PetTest" name="TestPutPet" time="3.887"/>
  <testcase classname="api.demo.tests.ExtentReport_PetTest" name="TestDeletePet" time="1.834"/>
  <testcase classname="api.demo.tests.PetTest" name="TestPostPet" time="1.974"/>
  <testcase classname="api.demo.tests.PetTest" name="TestGetpet" time="3.166"/>
  <testcase classname="api.demo.tests.PetTest" name="TestPutPet" time="4.194"/>
  <testcase classname="api.demo.tests.PetTest" name="TestDeletePet" time="1.832"/>
</testsuite> <!-- Default test -->
